"""Register a CPU memory pool with the untouched Python binding, for a C++ node to read.

`register_memory_pool(tensor_info, "cpu")` writes a `DORADMA` segment with a
full data region and `ipc_present = 0` — the same bytes the C++ `unified`
transport writes, except for one key the C++ writer adds to the metadata JSON
(`transport`) and Python does not. That is what makes cross-language interop
work on a platform with no CUDA IPC: nothing in the Python binding is patched
here, and the C++ consumer maps the segment the same way it maps one of its own.

`"cuda"` as the receiver device would fail at registration on this machine, by
design: the Python binding hard-requires a `cudaIpcGetMemHandle` export, which
an integrated GPU does not support. Only the *sender* half of Python is stuck
there; a CPU pool feeds a CUDA C++ consumer perfectly well, which is what
`dataflow-python-interop-cuda.yml` runs.

The pool id is **generated by the binding** (`pool_<node-id>_<counter>`), not
chosen by the caller, so it is published on the `pool_id` output and the C++
consumer maps whatever it is told. It never derives the id, and it never
derives the segment name — that comes from the daemon.

The two nodes run in lockstep: this node publishes one notice and then waits
for the consumer's ack before writing again, so the consumer's checks never
race a write. `write_memory_pool` is a non-blocking overwrite, and the turn
taking is the caller's job.
"""

import numpy as np
import pyarrow as pa
from dora import Node

# The ring the consumer checks, byte for byte. Mirrored in `nodes/protocol.h`.
SLOT_BYTES = 1024
SLOT_COUNT = 16

# Notice kinds, mirroring `Kind` in `nodes/protocol.h`. `kAbandoned` has no
# Python spelling — there is no way to abandon a write cycle through this API,
# which is one of the reasons this dataflow cannot reuse the C++ example's
# consumer.
HELLO = 0
FRAME = 1
FREED = 3

FRAME_STEPS = 20
FREE_STEP = FRAME_STEPS + 1


def tensor_info(payload: np.ndarray) -> dict:
    """Describe `payload` the way `dora.cuda.get_tensor_info` describes a tensor.

    Spelled out rather than imported because `dora.cuda` pulls in torch, which
    this example does not otherwise need. `device` is required — the binding
    reads it to decide whether the source pointer is a device pointer.
    """
    return {
        "ptr": payload.ctypes.data,
        "size": payload.nbytes,
        "dtype": "uint8",
        "shape": list(payload.shape),
        "device": "cpu",
    }


def notice(step: int, kind: int, slot: int, value: int) -> pa.Array:
    """The four bytes the consumer reads: `{step, kind, slot, value}`."""
    return pa.array([step, kind, slot, value], type=pa.uint8())


def main() -> None:
    node = Node()

    payload = np.zeros(SLOT_BYTES * SLOT_COUNT, dtype=np.uint8)
    pool = node.register_memory_pool(tensor_info(payload), "cpu")
    pool_id = pool[0].as_py()
    print(f"[python-sender] registered pool `{pool_id}`", flush=True)

    published = 0  # the step the consumer still owes an ack for; 0 is the hello
    for event in node:
        if event["type"] != "INPUT":
            continue

        if event["id"] == "tick":
            # Repeated until the consumer has mapped the pool, so the handshake
            # does not depend on which node starts first.
            if published == 0:
                _bad = pool_id[:-1] + str(int(pool_id[-1]) + 1)  # MUTATION
                node.send_output(
                    "pool_id", pa.array(list(_bad.encode()), type=pa.uint8())
                )
                node.send_output("notice", notice(0, HELLO, 0, 0))
            continue

        if event["id"] != "ack" or event["value"][0].as_py() != published:
            continue

        published += 1
        if published <= FRAME_STEPS:
            slot = (published - 1) % SLOT_COUNT
            value = published
            payload[slot * SLOT_BYTES : (slot + 1) * SLOT_BYTES] = value
            # Writes the whole 16 KiB, so the slots this step did not touch keep
            # what earlier steps put there — which is what the consumer's ring
            # model checks.
            node.write_memory_pool(pool, tensor_info(payload))
            node.send_output("notice", notice(published, FRAME, slot, value))
        elif published == FREE_STEP:
            node.free_memory_pool(pool)
            print(f"[python-sender] freed pool `{pool_id}`", flush=True)
            node.send_output("notice", notice(published, FREED, 0, 0))
        else:
            break

    if published <= FREE_STEP:
        raise SystemExit(
            f"[python-sender] stopped at step {published} of {FREE_STEP} "
            "without completing the script"
        )
    print(f"[python-sender] completed {FRAME_STEPS} frames and the free", flush=True)


if __name__ == "__main__":
    main()
