#![cfg(feature = "rmw-zenoh")]

use dora_ros2_bridge::transport::zenoh::compatibility::{RosTypeIdentity, TypeHash};
use dora_ros2_bridge::transport::{
    Durability, History, Liveliness, Reliability, Ros2Qos,
    zenoh::{
        attachment::Attachment,
        keyexpr::{DataKey, EntityKind, LivelinessKey, TopicToken},
        qos::ZenohQosMapping,
    },
};

#[test]
fn data_keys_cover_domains_and_nested_names() {
    let identity = RosTypeIdentity {
        ros_name: "std_msgs/msg/String".into(),
        dds_name: "std_msgs::msg::dds_::String_".into(),
        hash: TypeHash::HumbleUnsupported,
    };
    assert_eq!(
        DataKey::new(0, "/chatter", &identity).unwrap().as_str(),
        "0/chatter/std_msgs::msg::dds_::String_/TypeHashNotSupported"
    );
    assert_eq!(
        DataKey::new(42, "/robot/_hidden/chatter", &identity)
            .unwrap()
            .as_str(),
        "42/robot/_hidden/chatter/std_msgs::msg::dds_::String_/TypeHashNotSupported"
    );
}

#[test]
fn all_liveliness_entity_kinds_round_trip() {
    for kind in [
        EntityKind::Node,
        EntityKind::Publisher,
        EntityKind::Subscription,
        EntityKind::Service,
        EntityKind::Client,
    ] {
        let key = if kind == EntityKind::Node {
            LivelinessKey::node(42, "zid", "nid", "eid", "/", "/robot/ns", "node").unwrap()
        } else {
            LivelinessKey::endpoint(
                42,
                "zid",
                "nid",
                "eid",
                kind,
                "/",
                "/robot/ns",
                "node",
                TopicToken {
                    name: "/chatter".into(),
                    type_name: "std_msgs::msg::dds_::String_".into(),
                    type_hash: "TypeHashNotSupported".into(),
                    qos: "2::,1:,:,:,,,".into(),
                },
            )
            .unwrap()
        };
        assert_eq!(LivelinessKey::parse(key.as_str()).unwrap(), key);
    }
}

#[test]
fn attachment_matches_upstream_serializer_and_rejects_trailing_bytes() {
    let attachment = Attachment {
        sequence_number: 7,
        source_timestamp_ns: 1_725_000_000_000_000_000,
        gid: [0x2a; 16],
    };
    let bytes = attachment.encode().unwrap();
    assert_eq!(
        bytes
            .iter()
            .map(|byte| format!("{byte:02x}"))
            .collect::<String>(),
        include_str!("fixtures/rmw_zenoh/attachment-seq7.hex").trim()
    );
    assert_eq!(Attachment::decode(&bytes).unwrap(), attachment);
    let mut extra = bytes;
    extra.push(0);
    assert!(Attachment::decode(&extra).is_err());
    assert!(Attachment::decode(&[0; 3]).is_err());
}

#[test]
fn attachment_accepts_sequence_and_timestamp_boundaries() {
    for value in [i64::MIN, -1, 0, i64::MAX] {
        let attachment = Attachment {
            sequence_number: value,
            source_timestamp_ns: value,
            gid: [0; 16],
        };
        assert_eq!(
            Attachment::decode(&attachment.encode().unwrap()).unwrap(),
            attachment
        );
    }
}

#[test]
fn qos_default_and_non_default_match_rmw_components() {
    assert_eq!(
        ZenohQosMapping::from_ros_qos(&Ros2Qos::default()).to_string(),
        "2::,1:,:,:,,"
    );
    let qos = Ros2Qos {
        reliability: Reliability::BestEffort,
        history: History::KeepLast { depth: 7 },
        ..Ros2Qos::default()
    };
    assert_eq!(
        ZenohQosMapping::from_ros_qos(&qos).to_string(),
        "2::,7:,:,:,,"
    );
    // Manual liveliness + transient-local durability: the liveliness kind ("3")
    // must land in the *first* subfield of the trailing group (kind,lease_sec,
    // lease_nsec), i.e. `3,,` — not `,3,`. This guards the rmw_zenoh_cpp wire
    // parity that the buggy `,{liveliness},` layout silently broke.
    let qos = Ros2Qos {
        durability: Durability::TransientLocal,
        liveliness: Liveliness::ManualByTopic {
            lease_duration: None,
        },
        ..Ros2Qos::default()
    };
    assert_eq!(
        ZenohQosMapping::from_ros_qos(&qos).to_string(),
        "2:1:,1:,:,:3,,"
    );
}

#[test]
fn malformed_components_fail_closed() {
    assert!(LivelinessKey::parse("@ros2_lv/0/z/n/i/NN//%/node").is_err());
    assert!(
        DataKey::new(
            0,
            "/bad/**",
            &RosTypeIdentity {
                ros_name: "x/msg/X".into(),
                dds_name: "x::msg::dds_::X_".into(),
                hash: TypeHash::HumbleUnsupported
            }
        )
        .is_err()
    );
}

// ---------------------------------------------------------------------------
// Real-peer parity: fixtures below were CAPTURED from a live ROS 2 Humble
// `rmw_zenoh_cpp` 0.1.8 publisher (not generated by the code under test), so
// these assertions verify wire parity against upstream, not self-consistency.
// See fixtures/rmw_zenoh/README.md for how they were captured.
// ---------------------------------------------------------------------------

fn hex_to_bytes(hex: &str) -> Vec<u8> {
    let hex = hex.trim();
    (0..hex.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).expect("valid hex fixture"))
        .collect()
}

#[test]
fn attachment_round_trips_real_rmw_zenoh_cpp_bytes() {
    let real = hex_to_bytes(include_str!(
        "fixtures/rmw_zenoh/attachment-real-humble.hex"
    ));
    let decoded = Attachment::decode(&real).expect("our decoder must accept real peer bytes");
    // Re-encoding the decoded fields must reproduce the exact peer bytes: this
    // proves our attachment codec matches the rmw_zenoh_cpp wire layout — i64
    // sequence, i64 source timestamp, and a length-prefixed 16-byte gid (the
    // `0x10` prefix a prior review doubted is present in both directions).
    assert_eq!(decoded.encode().unwrap(), real);
}

#[test]
fn data_key_matches_real_rmw_zenoh_cpp_peer() {
    let identity = RosTypeIdentity {
        ros_name: "std_msgs/msg/String".into(),
        dds_name: "std_msgs::msg::dds_::String_".into(),
        hash: TypeHash::HumbleUnsupported,
    };
    assert_eq!(
        DataKey::new(0, "/chatter", &identity).unwrap().as_str(),
        "0/chatter/std_msgs::msg::dds_::String_/TypeHashNotSupported"
    );
}

#[test]
fn liveliness_token_and_qos_match_real_rmw_zenoh_cpp_peer() {
    let token = include_str!("fixtures/rmw_zenoh/liveliness-token-real-humble.txt").trim();
    let key = LivelinessKey::parse(token).expect("our parser must accept a real peer token");
    let topic = key.topic.expect("a publisher token carries a topic");
    assert_eq!(topic.name, "/chatter");
    assert_eq!(topic.type_name, "std_msgs::msg::dds_::String_");
    assert_eq!(topic.type_hash, "TypeHashNotSupported");
    // The QoS component the real peer embedded (Reliable / TransientLocal /
    // KeepLast(1) / Automatic-liveliness publisher) must match our encoder
    // byte-for-byte — this validates the liveliness-subfield ordering against a
    // real peer, not just against our own output.
    assert_eq!(topic.qos, ":1:,1:,:,:,,");
    let qos = Ros2Qos {
        reliability: Reliability::Reliable {
            max_blocking_time: std::time::Duration::ZERO,
        },
        durability: Durability::TransientLocal,
        history: History::KeepLast { depth: 1 },
        liveliness: Liveliness::Automatic {
            lease_duration: None,
        },
    };
    assert_eq!(ZenohQosMapping::from_ros_qos(&qos).to_string(), topic.qos);
}
