#![allow(clippy::borrow_deref_ref)] // clippy warns about code generated by #[pymethods]

use std::collections::HashMap;
use std::env::current_dir;
use std::path::PathBuf;
use std::sync::{Arc, LazyLock};
use std::time::Duration;
use tokio::sync::Mutex;

use arrow::array::{Array, BinaryArray, StringArray};
use arrow::datatypes::DataType;
use arrow::pyarrow::{FromPyArrow, ToPyArrow};
use dora_download::download_file;
use dora_node_api::dora_core::config::NodeId;
use dora_node_api::dora_core::descriptor::source_is_url;
use dora_node_api::merged::{MergeExternalSend, MergedEvent};
use dora_node_api::{
    DataflowId, DoraNode, EventStream, Metadata, MetadataParameters, Parameter, TryRecvError,
    init_tracing,
};
use dora_operator_api_python::{
    DelayedCleanup, NodeCleanupHandle, PyEvent, metadata_to_pydict, pydict_to_metadata,
};
use dora_ros2_bridge_python::Ros2Subscription;
use eyre::{Context, ContextCompat};
use shared_memory_extended::ShmemConf;

use futures::{Stream, StreamExt};
use pyo3::prelude::*;
use pyo3::types::{PyBytes, PyDict, PyString, PyTuple};
use pyo3_special_method_derive::{Dict, Dir, Repr, Str};
use tokio::runtime::{Builder, Runtime};
use tracing::{Level, span};

/// Pool size for shmem ring buffer and GPU buffer slots.
const DMA_POOL_SIZE: usize = 3;

/// Pre-compiled CUDA DMA helper module. Compiled once (at first use) and reused
/// across all iterations to eliminate per-call PyModule::from_code overhead.
/// Maintains persistent state: pinned host pointers, pre-allocated GPU buffers.
static CUDA_HELPERS: LazyLock<std::sync::Mutex<Option<Py<PyModule>>>> =
    LazyLock::new(|| std::sync::Mutex::new(None));

/// Round-robin slot index for GPU buffer pool (receiver side).
static DMA_SLOT: LazyLock<std::sync::Mutex<usize>> =
    LazyLock::new(|| std::sync::Mutex::new(0));

/// Counter to make pinned memory buffer IDs unique across iterations.
static PINNED_COUNTER: LazyLock<std::sync::Mutex<u64>> =
    LazyLock::new(|| std::sync::Mutex::new(0));

/// Local tracking of freed pool buffers for double-free/read-after-free detection.
/// Pool mode bypasses daemon metadata queries, so we need local state for warnings.
static FREED_POOL_BUFFERS: LazyLock<std::sync::Mutex<HashMap<String, usize>>> =
    LazyLock::new(|| std::sync::Mutex::new(HashMap::new()));

/// Per-slot persistent pool state.
/// Keeping Shmem alive prevents munmap, preserving stable mmap addresses
/// for pool-hit detection across `register_pinned_memory` calls.
///
/// # Safety
/// `Shmem` is not `Send + Sync` due to raw pointer fields, but `PoolSlot`
/// is always stored behind a `Mutex` and `_shmem` is never accessed after
/// initialization — it is only kept alive for its destructor.
struct PoolSlot {
    _shmem: shared_memory_extended::Shmem,
    base: u64,
    size: usize,
    gpu_va: u64,
}

unsafe impl Send for PoolSlot {}
unsafe impl Sync for PoolSlot {}

/// Persistent pool storage — stable mmap addresses for zero-copy detection.
static PINNED_POOL: LazyLock<std::sync::Mutex<[Option<PoolSlot>; DMA_POOL_SIZE]>> =
    LazyLock::new(|| std::sync::Mutex::new([None, None, None]));

/// Receiver-side GPU VA cache per pool slot.
/// Keeps Shmem alive to prevent munmap, preserving stable mmap addresses
/// and valid GPU VAs for zero-copy reads across iterations.
struct RecvGpuSlot {
    _shmem: shared_memory_extended::Shmem,
    gpu_va: u64,
}
unsafe impl Send for RecvGpuSlot {}
unsafe impl Sync for RecvGpuSlot {}

/// Receiver-side per-slot cache keeping Shmem alive + GPU VA for zero-copy reads.
/// Set up lazily in try_doradma_read: open shmem, cudaHostRegister,
/// cudaHostGetDevicePointer, then cache both Shmem and GPU VA.
static RECV_GPU_VA: LazyLock<std::sync::Mutex<[Option<RecvGpuSlot>; DMA_POOL_SIZE]>> =
    LazyLock::new(|| std::sync::Mutex::new([None, None, None]));

/// Get (or compile) the persistent CUDA DMA helper module.
///
/// Compiled once at first use and reused across all subsequent iterations.
/// The module maintains internal state for pinned host pointers and GPU buffers,
/// eliminating per-call cudaHostRegister/cudaMalloc/cudaFree/shm_open overhead.
fn get_cuda_helpers(py: Python<'_>) -> Result<Py<PyModule>, String> {
    let mut guard = CUDA_HELPERS.lock().unwrap();
    if let Some(ref module) = *guard {
        return Ok(module.clone_ref(py));
    }

    let code = r#"
import ctypes
_lib = ctypes.CDLL('libcudart.so')

_lib.cudaHostRegister.restype = ctypes.c_int
_lib.cudaHostRegister.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_uint]

_lib.cudaHostUnregister.restype = ctypes.c_int
_lib.cudaHostUnregister.argtypes = [ctypes.c_void_p]

_lib.cudaMalloc.restype = ctypes.c_int
_lib.cudaMalloc.argtypes = [ctypes.POINTER(ctypes.c_void_p), ctypes.c_size_t]

_lib.cudaMemcpy.restype = ctypes.c_int
_lib.cudaMemcpy.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_int]

_lib.cudaFree.restype = ctypes.c_int
_lib.cudaFree.argtypes = [ctypes.c_void_p]

_lib.cudaDeviceSynchronize.restype = ctypes.c_int

_lib.cudaHostGetDevicePointer.restype = ctypes.c_int
_lib.cudaHostGetDevicePointer.argtypes = [ctypes.POINTER(ctypes.c_void_p), ctypes.c_void_p, ctypes.c_uint]

cudaMemcpyHostToDevice = 1

# Persistent state: pinned host pointers and pre-allocated GPU buffers
_pinned = {}      # key=(ptr,size) -> True
_gpu_bufs = {}    # slot -> (d_ptr, size)

def _register_host(ptr, size):
    """Pin host memory. No-op if already pinned (idempotent)."""
    key = (ptr, size)
    if key in _pinned:
        return
    err = _lib.cudaHostRegister(ctypes.c_void_p(ptr), size, 0)
    if err != 0 and err != 712:
        raise RuntimeError(f'cudaHostRegister(0x{ptr:x}, {size}) failed: {err}')
    _pinned[key] = True

def _get_device_ptr(host_ptr):
    """Get a GPU virtual address for a pinned host memory region.

    Returns a GPU VA that can be used in cudaMemcpy and CUDA kernels.
    Must be called AFTER _register_host on the same host_ptr.
    The GPU VA is valid in the current CUDA context only.
    """
    d_ptr = ctypes.c_void_p()
    err = _lib.cudaHostGetDevicePointer(ctypes.byref(d_ptr), ctypes.c_void_p(host_ptr), 0)
    if err != 0:
        raise RuntimeError(f'cudaHostGetDevicePointer(0x{host_ptr:x}) failed: {err}')
    return d_ptr.value


def _cuda_memcpy(dst, src, size, kind):
    """cudaMemcpy wrapper. kind: 1=H2D, 2=D2H, 3=D2D."""
    err = _lib.cudaMemcpy(ctypes.c_void_p(dst), ctypes.c_void_p(src), size, kind)
    if err != 0:
        raise RuntimeError(f"cudaMemcpy(0x{dst:x}, 0x{src:x}, {size}, {kind}) failed: {err}")
    _lib.cudaDeviceSynchronize()

def _get_gpu_buf(slot, size):
    """Get or allocate a GPU buffer for the given slot. Reuses when size matches."""
    if slot in _gpu_bufs and _gpu_bufs[slot][1] >= size:
        return _gpu_bufs[slot][0]
    if slot in _gpu_bufs:
        _lib.cudaFree(ctypes.c_void_p(_gpu_bufs[slot][0]))
    d_ptr = ctypes.c_void_p()
    err = _lib.cudaMalloc(ctypes.byref(d_ptr), size)
    if err != 0:
        raise RuntimeError(f'cudaMalloc({size}) failed: {err}')
    _gpu_bufs[slot] = (d_ptr.value, size)
    return d_ptr.value

def dma_copy(ptr, size, slot):
    """DMA transfer from pinned host to pre-allocated GPU buffer.
    Returns the device pointer. Pins host memory if not already pinned."""
    _register_host(ptr, size)
    d_ptr = _get_gpu_buf(slot, size)
    err = _lib.cudaMemcpy(
        ctypes.c_void_p(d_ptr),
        ctypes.c_void_p(ptr),
        size,
        cudaMemcpyHostToDevice,
    )
    if err != 0:
        raise RuntimeError(f'cudaMemcpy failed: {err}')
    _lib.cudaDeviceSynchronize()
    return d_ptr

"#;

    let code_cstr = std::ffi::CString::new(code)
        .map_err(|e| format!("CString: {}", e))?;
    let bound_module = PyModule::from_code(py, code_cstr.as_c_str(), c"_cuda_helpers.py", c"_cuda_helpers")
        .map_err(|e| format!("CUDA helper compile failed: {}", e))?;
    let module_ref: Py<PyModule> = bound_module.unbind();
    *guard = Some(module_ref.clone_ref(py));
    Ok(module_ref)
}

/// DMA transfer using the persistent CUDA helper module.
/// Uses pre-allocated GPU buffers and pre-pinned host memory (idempotent pinning).
/// Eliminates per-call: PyModule::from_code, cudaHostRegister, cudaMalloc, cudaFree.
fn dma_to_gpu_pooled(py: Python<'_>, host_ptr: u64, size: usize) -> Result<u64, String> {
    if host_ptr == 0 || size == 0 {
        return Err("Invalid host pointer or size".to_string());
    }

    let helpers = get_cuda_helpers(py)?;
    let slot = {
        let mut s = DMA_SLOT.lock().unwrap();
        let current = *s;
        *s = (current + 1) % DMA_POOL_SIZE;
        current
    };

    let bound = helpers.bind(py);
    let result = bound
        .call_method1("dma_copy", (host_ptr, size, slot))
        .map_err(|e| format!("dma_copy failed: {}", e))?;
    result
        .extract::<u64>()
        .map_err(|e| format!("extract device_ptr: {}", e))
}

static RUNTIME: LazyLock<Runtime> = LazyLock::new(|| {
    Builder::new_multi_thread()
        .worker_threads(4)
        .enable_all()
        .build()
        .context("Failed to create Tokio runtime")
        .unwrap()
});

/// Consume a Python `logging.LogRecord` and emit a Rust `tracing::Event` instead.
#[pyfunction]
fn host_log<'py>(record: Bound<'py, PyAny>) -> PyResult<()> {
    let level = record.getattr("levelno")?.extract::<u8>()?;
    let message = record.getattr("getMessage")?.call0()?.to_string();
    let pathname = record.getattr("pathname")?.to_string();
    let lineno = record.getattr("lineno")?.to_string();
    let target = record.getattr("name")?.to_string();

    RUNTIME.spawn(async move {
    if level.ge(&40u8) {
        let span = span!(Level::ERROR, "dora.python.log.error", file=pathname, line=lineno, %target, %message);
        let _enter = span.enter();
        tracing::event!(tracing::Level::ERROR, file=pathname, line=lineno, %target, %message);
    } else if level.ge(&30u8) {
        let span = span!(Level::WARN, "dora.python.log.warn", file=pathname, line=lineno, %target, %message);
        let _enter = span.enter();
        tracing::event!(tracing::Level::WARN, file=pathname, line=lineno, %target, %message);
    } else if level.ge(&20u8){
        let span = span!(Level::INFO, "dora.python.log.info", file=pathname, line=lineno, %target, %message);
        let _enter = span.enter();
        tracing::event!(tracing::Level::INFO, file=pathname, line=lineno, %target, %message);
    } else if level.ge(&10u8) {
        let span = span!(Level::DEBUG, "dora.python.log.debug", file=pathname, line=lineno, %target, %message);
        let _enter = span.enter();
        tracing::event!(tracing::Level::DEBUG, file=pathname, line=lineno, %target, %message);
    } else {
        let span = span!(Level::TRACE, "dora.python.log.trace", file=pathname, line=lineno, %target, %message);
        let _enter = span.enter();
        tracing::event!(tracing::Level::TRACE, file=pathname, line=lineno, %target, %message);
    }
    });
    Ok(())
}

/// Modifies the Python `logging` module to deliver its log messages to the host `tracing::Subscriber` by default.
/// To achieve this goal, the following changes are made to the module:
/// - A new builtin function `logging.host_log` transcodes `logging.LogRecord`s to `tracing::Event`s. This function
///   is not exported in `logging.__all__`, as it is not intended to be called directly.
/// - A new class `logging.HostHandler` provides a `logging.Handler` that delivers all records to `host_log`.
/// - `logging.basicConfig` is changed to use `logging.HostHandler` by default.
///
/// Since any call like `logging.warn(...)` sets up logging via `logging.basicConfig`, all log messages are now
/// delivered to `crate::host_log`, which will send them to `tracing::event!`.
pub fn setup_logging(py: Python) -> PyResult<()> {
    let logging = py.import("logging")?;
    logging.setattr("host_log", wrap_pyfunction!(host_log, &logging)?)?;
    py.run(
        cr#"
class HostHandler(Handler):
	def __init__(self, level=0):
		super().__init__(level=level)
	
	def emit(self, record):
		host_log(record)

oldBasicConfig = basicConfig

def basicConfig(*pargs, **kwargs):
	if "handlers" not in kwargs:
		kwargs["handlers"] = [HostHandler()]
	else:
		kwargs["handlers"].append(HostHandler())
	if "level" not in kwargs:
		kwargs["level"] = 0

	return oldBasicConfig(*pargs, **kwargs)
"#,
        Some(&logging.dict()),
        None,
    )?;

    let all = logging.index()?;
    all.append("HostHandler")?;

    Ok(())
}
/// The custom node API lets you integrate `dora` into your application.
/// It allows you to retrieve input and send output in any fashion you want.
///
/// Use with:
///
/// ```python
/// from dora import Node
///
/// node = Node()
/// ```
///
/// :type node_id: str, optional
#[pyclass]
#[derive(Dir, Dict, Str, Repr)]
pub struct Node {
    events: Events,
    node: DelayedCleanup<DoraNode>,

    dataflow_id: DataflowId,
    node_id: NodeId,
}

#[pymethods]
impl Node {
    #[new]
    #[pyo3(signature = (node_id=None, daemon_port=None))]
    pub fn new(node_id: Option<String>, daemon_port: Option<u16>) -> eyre::Result<Self> {
        let (node, events) = if let Some(node_id) = node_id {
            if let Some(port) = daemon_port {
                // Explicit port: always use builder with dynamic mode
                DoraNode::builder()
                    .node_id(NodeId::from(node_id))
                    .dynamic()
                    .daemon_port(port)
                    .build()
            } else {
                // No explicit port: try DORA_NODE_CONFIG first, fall back to dynamic
                DoraNode::init_flexible(NodeId::from(node_id))
            }
            .context("Could not setup node from node id. Make sure to have a running dataflow with this dynamic node")?
        } else {
            DoraNode::init_from_env().context("Could not initiate node from environment variable. For dynamic node, please add a node id in the initialization function.")?
        };
        let id = node.id().clone();
        let dataflow_id = node.dataflow_id().clone();
        RUNTIME.spawn(async move {
            let _guard = init_tracing(&id, &dataflow_id).unwrap();
            loop {
                tokio::time::sleep(std::time::Duration::from_secs(1)).await;
            }
        });

        let dataflow_id = *node.dataflow_id();
        let node_id = node.id().clone();
        let node = DelayedCleanup::new(node);
        let cleanup_handle = NodeCleanupHandle {
            _handles: Arc::new(node.handle()),
        };

        Python::with_gil(|py| {
            // Extend the `logging` module to interact with tracing
            setup_logging(py)
        })?;

        Ok(Node {
            events: Events {
                inner: Arc::new(Mutex::new(EventsInner::Dora(events))),
                _cleanup_handle: cleanup_handle,
            },
            dataflow_id,
            node_id,
            node,
        })
    }

    /// `.next()` gives you the next input that the node has received.
    /// It blocks until the next event becomes available.
    /// You can use timeout in seconds to return if no input is available.
    /// It will return `None` when all senders has been dropped.
    ///
    /// ```python
    /// event = node.next()
    /// ```
    ///
    /// You can also iterate over the event stream with a loop
    ///
    /// ```python
    /// for event in node:
    ///    match event["type"]:
    ///        case "INPUT":
    ///            match event["id"]:
    ///                 case "image":
    /// ```
    ///
    /// :type timeout: float, optional
    /// :rtype: dict
    #[pyo3(signature = (timeout=None))]
    #[allow(clippy::should_implement_trait)]
    pub fn next(&self, py: Python, timeout: Option<f32>) -> PyResult<Option<Py<PyDict>>> {
        let event = py.allow_threads(|| self.events.recv(timeout.map(Duration::from_secs_f32)))?;
        if let Some(event) = event {
            let dict = event
                .to_py_dict(py)
                .context("Could not convert event into a dict")?;
            Ok(Some(dict))
        } else {
            Ok(None)
        }
    }

    /// `.drain()` gives you all available inputs that the node has received.
    /// It does not block until the next event becomes available.
    ///
    /// ```python
    /// events = node.drain()
    /// for event in events:
    ///     print(event)
    /// ```
    ///
    /// :rtype: list[dict]
    #[allow(clippy::should_implement_trait)]
    pub fn drain(&self, py: Python) -> PyResult<Vec<Py<PyDict>>> {
        let events = self
            .events
            .drain()
            .context("Could not drain events. Channel is closed")?
            .into_iter()
            .map(|event| {
                event
                    .to_py_dict(py)
                    .context("Could not convert event into a dict")
                    .unwrap_or_else(|_| PyDict::new(py).into())
            })
            .collect();
        Ok(events)
    }

    /// `.try_recv()` gives you the next input in the queue that the node has received.
    /// It does not block until the next event becomes available.
    ///
    /// ```python
    /// event = events.try_recv()
    ///     print(event)
    /// ```
    ///
    /// :rtype: dict
    #[allow(clippy::should_implement_trait)]
    pub fn try_recv(&mut self, py: Python) -> PyResult<Option<Py<PyDict>>> {
        Ok(match self.events.try_recv()? {
            Ok(event) => match event.to_py_dict(py) {
                Ok(dict) => Some(dict),
                Err(_) => None,
            },
            Err(_) => None,
        })
    }

    /// Check if there are any buffered events in the event stream.
    ///
    /// :rtype: bool
    #[allow(clippy::should_implement_trait)]
    pub fn is_empty(&self) -> bool {
        self.events.is_empty()
    }

    /// `.recv_async()` gives you the next input that the node has received asynchronously.
    /// It does not blocks until the next event becomes available.
    /// You can use timeout in seconds to return if no input is available.
    /// It will return an Error if the timeout is reached.
    /// It will return `None` when all senders has been dropped.
    ///
    /// warning::
    ///     This feature is experimental as pyo3 async (rust-python FFI) is still in development.
    ///
    /// ```python
    /// event = await node.recv_async()
    /// ```
    ///
    /// You can also iterate over the event stream with a loop
    ///
    /// :type timeout: float, optional
    /// :rtype: dict
    #[pyo3(signature = (timeout=None))]
    #[allow(clippy::should_implement_trait)]
    pub async fn recv_async(&self, timeout: Option<f32>) -> PyResult<Option<Py<PyDict>>> {
        let event = self
            .events
            .recv_async_timeout(timeout.map(Duration::from_secs_f32))
            .await?;
        if let Some(event) = event {
            // Get python
            Python::with_gil(|py| {
                let dict = event
                    .to_py_dict(py)
                    .context("Could not convert event into a dict")?;

                Ok(Some(dict))
            })
        } else {
            Ok(None)
        }
    }

    /// You can iterate over the event stream with a loop
    ///
    /// ```python
    /// for event in node:
    ///    match event["type"]:
    ///        case "INPUT":
    ///            match event["id"]:
    ///                 case "image":
    /// ```
    ///
    /// Default behaviour is to timeout after 2 seconds.
    ///
    /// :rtype: dict
    pub fn __next__(&self, py: Python) -> PyResult<Option<Py<PyDict>>> {
        self.next(py, None)
    }

    /// You can iterate over the event stream with a loop
    ///
    /// ```python
    /// for event in node:
    ///    match event["type"]:
    ///        case "INPUT":
    ///            match event["id"]:
    ///                 case "image":
    /// ```
    ///
    /// :rtype: dict
    fn __iter__(slf: PyRef<'_, Self>) -> PyRef<'_, Self> {
        slf
    }

    /// `send_output` send data from the node.
    ///
    /// ```python
    /// Args:
    ///    output_id: str,
    ///    data: pyarrow.Array,
    ///    metadata: Option[Dict],
    /// ```
    ///
    /// ex:
    ///
    /// ```python
    /// node.send_output("string", b"string", {"open_telemetry_context": "7632e76"})
    /// ```
    ///
    /// :type output_id: str
    /// :type data: pyarrow.Array
    /// :type metadata: dict, optional
    /// :rtype: None
    #[pyo3(signature = (output_id, data, metadata=None))]
    pub fn send_output(
        &self,
        output_id: String,
        data: PyObject,
        metadata: Option<Bound<'_, PyDict>>,
        py: Python,
    ) -> eyre::Result<()> {
        let parameters = pydict_to_metadata(metadata)?;

        if let Ok(py_bytes) = data.downcast_bound::<PyBytes>(py) {
            let data = py_bytes.as_bytes();
            self.node
                .get_mut()
                .send_output_bytes(output_id.into(), parameters, data.len(), data)
                .wrap_err("failed to send output")?;
        } else if let Ok(arrow_array) = arrow::array::ArrayData::from_pyarrow_bound(data.bind(py)) {
            self.node.get_mut().send_output(
                output_id.into(),
                parameters,
                arrow::array::make_array(arrow_array),
            )?;
        } else {
            eyre::bail!("invalid `data` type, must by `PyBytes` or arrow array")
        }

        Ok(())
    }

    /// Returns the full dataflow descriptor that this node is part of.
    ///
    /// This method returns the parsed dataflow YAML file.
    ///
    /// :rtype: dict
    pub fn dataflow_descriptor(&self, py: Python) -> eyre::Result<PyObject> {
        Ok(
            pythonize::pythonize(py, &self.node.get_mut().dataflow_descriptor()?)
                .map(|x| x.unbind())?,
        )
    }

    /// Returns the node configuration.
    ///
    /// :rtype: dict
    pub fn node_config(&self, py: Python) -> eyre::Result<PyObject> {
        Ok(pythonize::pythonize(py, &self.node.get_mut().node_config()).map(|x| x.unbind())?)
    }

    /// Returns the dataflow id.
    ///
    /// :rtype: str
    pub fn dataflow_id(&self) -> String {
        self.dataflow_id.to_string()
    }

    /// Merge an external event stream with dora main loop.
    /// This currently only work with ROS2.
    ///
    /// :type subscription: dora.Ros2Subscription
    /// :rtype: None
    pub fn merge_external_events(&self, subscription: &mut Ros2Subscription) -> eyre::Result<()> {
        let subscription = subscription.into_stream()?;
        let stream = futures::stream::poll_fn(move |cx| {
            let s = subscription.as_stream().map(|item| {
                match item.context("failed to read ROS2 message") {
                    Ok((value, _info)) => Python::with_gil(|py| {
                        value
                            .to_pyarrow(py)
                            .context("failed to convert value to pyarrow")
                            .unwrap_or_else(|err| err_to_pyany(err, py))
                    }),
                    Err(err) => Python::with_gil(|py| err_to_pyany(err, py)),
                }
            });
            futures::pin_mut!(s);
            s.poll_next_unpin(cx)
        });

        // take out the event stream and temporarily replace it with a dummy
        let mut inner = self.events.inner.blocking_lock();
        let events = std::mem::replace(
            &mut *inner,
            EventsInner::Merged(Box::new(futures::stream::empty())),
        );
        // update self.events with the merged stream
        *inner = EventsInner::Merged(Box::new(events.merge_external_send(Box::pin(stream))));

        Ok(())
    }

    /// Register pinned memory with the daemon.
    ///
    /// :param pinned_ptr: pyarrow array containing pointer to CPU tensor
    /// :param metadata: dictionary with tensor size, dtype, shape
    /// :rtype: pyarrow array containing shared memory identifier
    #[pyo3(signature = (pinned_ptr, metadata), name = "register_pinned_memory")]
    pub fn register_pinned_memory_internal(
        &self,
        pinned_ptr: PyObject,
        metadata: &Bound<'_, PyDict>,
        py: Python,
    ) -> eyre::Result<PyObject> {
        // Extract pointer value from pyarrow array
        let array_data_result = arrow::array::ArrayData::from_pyarrow_bound(pinned_ptr.bind(py));
        let array_data =
            array_data_result.wrap_err("failed to convert pinned_ptr to arrow array")?;
        let array = arrow::array::make_array(array_data);

        // The array should contain a single integer (pointer value)
        let ptr_value = if let Some(int64_array) =
            array.as_any().downcast_ref::<arrow::array::Int64Array>()
        {
            if int64_array.len() != 1 {
                eyre::bail!(
                    "expected Int64 array with exactly one element, got {}",
                    int64_array.len()
                );
            }
            let val = int64_array.value(0) as u64;
            val
        } else if let Some(int32_array) = array.as_any().downcast_ref::<arrow::array::Int32Array>()
        {
            if int32_array.len() != 1 {
                eyre::bail!(
                    "expected Int32 array with exactly one element, got {}",
                    int32_array.len()
                );
            }
            let val = int32_array.value(0) as u64;
            val
        } else {
            eyre::bail!(
                "pinned_ptr must be an integer array (Int32 or Int64), got {:?}",
                array.data_type()
            )
        };

        // Extract size from metadata
        let size: usize = metadata
            .get_item("size")
            .wrap_err("metadata missing 'size' key")?
            .unwrap()
            .extract()
            .wrap_err("failed to extract size as usize")?;

        // Validate inputs before creating shared memory
        if ptr_value == 0 {
            eyre::bail!("Invalid source pointer (NULL)");
        }
        if size == 0 || size > 1024 * 1024 * 1024 {
            eyre::bail!("Invalid size: {} bytes", size);
        }

        // --- Fast path: metadata header embedded in shmem ---
        // Header layout: [magic:8][json_len:8][data_offset:8][reserved:232][JSON:json_len][tensor_data:size]
        // This eliminates daemon round-trips: receiver reads metadata directly from shmem.
        const HEADER_SIZE: usize = 256;
        const HEADER_MAGIC: &[u8; 8] = b"DORADMA\x00";

        // Serialize metadata dict to JSON
        let json_bytes = py
            .import("json")
            .wrap_err("failed to import json")?
            .call_method1("dumps", (metadata,))
            .wrap_err("failed to serialize metadata to JSON")?
            .extract::<String>()
            .wrap_err("failed to extract JSON string")?
            .into_bytes();
        let json_len = json_bytes.len();
        // Pad metadata to 256-byte boundary for GPU tensor alignment requirements.
        // Without padding, CUDA kernels (e.g., torch_tensor[:5] += 100) may fail
        // with "misaligned address" on pinned host memory.
        const METADATA_ALIGN: usize = 256;
        let padded_json_len = ((json_len + METADATA_ALIGN - 1) / METADATA_ALIGN) * METADATA_ALIGN;
        let data_offset = HEADER_SIZE + padded_json_len;

        // --- Pool hit detection ---
        // Check if ptr_value falls within any existing pool slot's mmap range.
        // If so, data is already in shared memory → skip copy (true zero-copy registration).
        let pool_hit = {
            let pool = PINNED_POOL.lock().unwrap();
            let mut found = None;
            for (i, slot) in pool.iter().enumerate() {
                if let Some(ps) = slot {
                    let range_end = ps.base + ps.size as u64;
                    if ptr_value >= ps.base && ptr_value + size as u64 <= range_end {
                        found = Some(i);
                        break;
                    }
                }
            }
            found
        };

        // Slot: pool hit → reuse hit slot; miss → round-robin
        let pool_slot_idx = if let Some(hit) = pool_hit {
            hit
        } else {
            let mut s = DMA_SLOT.lock().unwrap();
            let current = *s;
            *s = (current + 1) % DMA_POOL_SIZE;
            current
        };
        let shmem_name = format!("dora_pool_{}", pool_slot_idx);

        // Data offset: pool hit → actual offset in pool; miss → standard (header + json)
        let data_offset_actual = if let Some(hit) = pool_hit {
            let pool = PINNED_POOL.lock().unwrap();
            let ps = pool[hit].as_ref().unwrap();
            (ptr_value - ps.base) as usize
        } else {
            data_offset
        };
        let total_size_actual = data_offset_actual + size;

        // Create or reuse shmem
        let mut shmem = match ShmemConf::new()
            .os_id(&shmem_name)
            .size(total_size_actual)
            .writable(true)
            .create()
        {
            Ok(s) => s,
            Err(_) => {
                ShmemConf::new()
                    .os_id(&shmem_name)
                    .writable(true)
                    .open()
                    .wrap_err("failed to open existing pool shared memory")?
            }
        };

        let shmem_ptr = unsafe { shmem.as_slice_mut().as_mut_ptr() };
        // Write DORADMA header (always: magic, json_len, data_offset, JSON)
        unsafe {
            std::ptr::copy_nonoverlapping(HEADER_MAGIC.as_ptr(), shmem_ptr, 8);
            let json_len_le = (json_len as u64).to_le_bytes();
            std::ptr::copy_nonoverlapping(json_len_le.as_ptr(), shmem_ptr.add(8), 8);
            let data_off_le = (data_offset_actual as u64).to_le_bytes();
            std::ptr::copy_nonoverlapping(data_off_le.as_ptr(), shmem_ptr.add(16), 8);
            // Write JSON metadata at offset 256
            std::ptr::copy_nonoverlapping(json_bytes.as_ptr(), shmem_ptr.add(HEADER_SIZE), json_len);
        }

        // Pin pool memory with CUDA (sender-side page-locking, idempotent).
        // Gets GPU VA for zero-copy receiver reads and for cudaMemcpy (CUDA tensors).
        let mut sender_gpu_va = 0u64;
        let mut cuda_registered = false;
        if let Ok(helpers) = get_cuda_helpers(py) {
            let bound = helpers.bind(py);
            let _ = bound.call_method1(
                "_register_host",
                (shmem_ptr as u64, total_size_actual),
            );
            if let Ok(va) = bound.call_method1(
                "_get_device_ptr",
                (shmem_ptr as u64,),
            ) {
                sender_gpu_va = va.extract::<u64>().unwrap_or(0);
                cuda_registered = sender_gpu_va != 0;
            }
        }

        // Write tensor data only on pool miss (pool hit = data already in shmem).
        // For CUDA tensors: DMA GPU→shmem via cudaMemcpy DeviceToHost (one copy).
        // For CPU tensors: direct memcpy to shmem.
        if pool_hit.is_none() {
            let is_cuda = metadata
                .get_item("is_cuda")
                .ok()
                .flatten()
                .and_then(|v| v.extract::<bool>().ok())
                .unwrap_or(false);

            if is_cuda && cuda_registered {
                // DMA copy: GPU VRAM → shmem (via GPU VA, single copy).
                // This implements the user's design:
                // "发送节点将页锁内存数据DMA拷贝到CUDA上"
                if let Ok(helpers) = get_cuda_helpers(py) {
                    let bound = helpers.bind(py);
                    let _ = bound.call_method1(
                        "_cuda_memcpy",
                        (sender_gpu_va + data_offset_actual as u64, ptr_value, size, 2u32), // DeviceToHost
                    );
                }
            } else {
                // CPU tensor or fallback: direct memcpy to shmem
                unsafe {
                    std::ptr::copy_nonoverlapping(ptr_value as *const u8, shmem_ptr.add(data_offset_actual), size);
                }
            }
        }

        shmem.set_owner(false);

        // Store in PINNED_POOL on first miss for future zero-copy.
        // Keeping Shmem alive prevents munmap → stable mmap addresses.
        if pool_hit.is_none() {
            let mut pool = PINNED_POOL.lock().unwrap();
            if pool[pool_slot_idx].is_none() {
                pool[pool_slot_idx] = Some(PoolSlot {
                    _shmem: shmem,
                    base: shmem_ptr as u64,
                    size: total_size_actual,
                    gpu_va: sender_gpu_va,
                });
            }
        }

        // Tag metadata for send_output event metadata
        let py_shmem_name = PyString::new(py, &shmem_name);
        metadata.set_item("shared_memory_name", py_shmem_name)?;
        metadata.set_item("ptr", ptr_value)?;

        // Generate buffer_id from pool slot + counter
        let counter = {
            let mut c = PINNED_COUNTER.lock().unwrap();
            *c += 1;
            *c
        };
        let buffer_id = format!("pool_{}_{}", pool_slot_idx, counter);

        // Register with daemon for lifecycle tracking (test5 cleanup).
        // The daemon's pinned_memory_table tracks unfreed entries for cleanup counting.
        // The DORADMA header still provides fast-path metadata reads (no daemon query needed).
        {
            // Extract metadata fields for daemon registration
            let dtype = metadata.get_item("dtype")?.unwrap().extract::<String>().unwrap_or_default();
            let shape_list: Vec<i64> = metadata
                .get_item("shape")?.unwrap()
                .extract::<Vec<i64>>().unwrap_or_default();

            use dora_node_api::dora_core::metadata::ArrowTypeInfo;
            use arrow::datatypes::DataType;

            let hlc = dora_node_api::dora_core::uhlc::HLC::default();
            let ts = hlc.new_timestamp();
            let mut params = dora_node_api::MetadataParameters::new();
            params.insert("ptr".to_string(), dora_node_api::Parameter::Integer(ptr_value as i64));
            params.insert("size".to_string(), dora_node_api::Parameter::Integer(size as i64));
            params.insert("dtype".to_string(), dora_node_api::Parameter::String(dtype));
            params.insert("shape".to_string(), dora_node_api::Parameter::ListInt(shape_list));
            params.insert("shared_memory_name".to_string(), dora_node_api::Parameter::String(shmem_name.clone()));
            params.insert("is_pinned".to_string(), dora_node_api::Parameter::Bool(true));
            params.insert("buffer_id".to_string(), dora_node_api::Parameter::String(buffer_id.clone()));

            let type_info = ArrowTypeInfo {
                data_type: DataType::Null,
                len: 0, null_count: 0, validity: None, offset: 0,
                buffer_offsets: vec![], child_data: vec![],
            };
            let meta = dora_node_api::Metadata::from_parameters(ts, type_info, params);
            if let Err(e) = self.node.get_mut().register_pinned_memory(buffer_id.clone(), meta) {
                tracing::warn!("[{}] failed to register pinned memory with daemon: {:#}", self.node_id, e);
            }
        }

        let buffer_id_array = arrow::array::StringArray::from(vec![buffer_id.clone()]);
        Ok(buffer_id_array.to_data().to_pyarrow(py).unwrap())
    }

    /// Read pinned memory from daemon and transfer to CUDA.
    ///
    /// :param pinned_buffer: pyarrow array containing shared memory identifier
    /// :param free: if True, free the pinned memory after reading
    /// :rtype: dictionary with cuda ptr, size, dtype, shape
    #[pyo3(signature = (pinned_buffer, free=true))]
    pub fn read_pinned_memory(
        &self,
        pinned_buffer: PyObject,
        free: bool,
        py: Python,
    ) -> eyre::Result<PyObject> {
        // Extract shared memory ID from pyarrow array
        let array_data_result = arrow::array::ArrayData::from_pyarrow_bound(pinned_buffer.bind(py));
        let array_data =
            array_data_result.wrap_err("failed to convert pinned_buffer to arrow array")?;
        let array = arrow::array::make_array(array_data);

        // The array should be a binary array containing the shared memory ID
        let shared_memory_id = match array.data_type() {
            DataType::Utf8 => {
                if let Some(string_array) = array.as_any().downcast_ref::<StringArray>() {
                    if string_array.len() != 1 {
                        eyre::bail!(
                            "expected string array with exactly one element, got {}",
                            string_array.len()
                        );
                    }
                    let id = string_array.value(0).to_string();
                    id
                } else {
                    eyre::bail!("failed to downcast Utf8 array to StringArray")
                }
            }
            DataType::Binary => {
                if let Some(binary_array) = array.as_any().downcast_ref::<BinaryArray>() {
                    if binary_array.len() != 1 {
                        eyre::bail!(
                            "expected binary array with exactly one element, got {}",
                            binary_array.len()
                        );
                    }
                    let bytes = binary_array.value(0);
                    String::from_utf8(bytes.to_vec())
                        .wrap_err("shared memory ID is not valid UTF-8")?
                } else {
                    eyre::bail!("failed to downcast Binary array to BinaryArray")
                }
            }
            _ => {
                eyre::bail!(
                    "READ/FREE: pinned_buffer must be a binary or string array, got {:?}",
                    array.data_type()
                )
            }
        };

        // --- DORADMA fast path: bypass daemon for pool-mode buffers ---
        // Buffer ID format: "pool_{slot}_{counter}" — metadata is embedded in shmem header.
        if shared_memory_id.starts_with("pool_") {
            if let Some(result) = self.try_doradma_read(&shared_memory_id, free, py)? {
                return Ok(result);
            }
            // DORADMA path failed (shmem missing, invalid header, etc.), fall through to daemon
        }

        // Always read without freeing to avoid race with shared memory deletion
        let metadata = match self.node.get_mut().read_pinned_memory(shared_memory_id.clone(), false) {
            Ok(m) => m,
            Err(_e) => {
                tracing::warn!(
                    "[{}]读取不存在的页锁内存{}",
                    self.node_id, shared_memory_id
                );
                // Return dummy values for read-after-free case
                let ptr_array = arrow::array::Int64Array::from(vec![0i64]);
                let pinned_ptr = ptr_array.to_data().to_pyarrow(py)
                    .map_err(|e| eyre::eyre!("failed to convert to pyarrow: {}", e))?;
                let dict = PyDict::new(py);
                dict.set_item("size", 0).ok();
                let tuple = PyTuple::new(py, &[pinned_ptr, dict.into()])?;
                return Ok(tuple.into());
            }
        };

        // Extract size from Rust metadata parameters for warnings
        let data_size: i64 = metadata
            .parameters
            .get("size")
            .and_then(|p| {
                if let Parameter::Integer(v) = p {
                    Some(*v)
                } else {
                    None
                }
            })
            .unwrap_or(0);
        let dict = metadata_to_pydict(&metadata, py)
            .wrap_err("failed to convert metadata to Python dictionary")?;
        let ptr_value: u64;
        if let Some(shmem_name_obj) = dict.get_item("shared_memory_name")? {
            let shmem_name: String = shmem_name_obj.extract()?;

            // Shared memory may have been unlinked by a prior free; handle gracefully
            let shmem = match ShmemConf::new().os_id(&shmem_name).open() {
                Ok(s) => s,
                Err(_) => {
                    tracing::warn!(
                        "[{}]读取不存在的页锁内存{}",
                        self.node_id, shared_memory_id
                    );
                    let ptr_array = arrow::array::Int64Array::from(vec![0i64]);
                    let pinned_ptr = ptr_array.to_data().to_pyarrow(py).unwrap_or_else(|_|
                        arrow::array::Int64Array::from(vec![0i64]).to_data().to_pyarrow(py).unwrap()
                    );
                    let empty_dict = PyDict::new(py);
                    empty_dict.set_item("size", 0).ok();
                    let tuple = PyTuple::new(py, &[pinned_ptr, empty_dict.into()])?;
                    return Ok(tuple.into());
                }
            };

            let host_ptr = shmem.as_ptr() as u64;

            let size: usize = match dict.get_item("size") {
                Ok(Some(v)) => v.extract::<usize>().unwrap_or(0),
                _ => 0,
            };
            let cuda_result = if size > 0 {
                dma_to_gpu_pooled(py, host_ptr, size)
            } else {
                Err("size is 0".to_string())
            };

            if let Ok(device_ptr) = cuda_result {
                dict.set_item("ptr", device_ptr as i64).ok();
                dict.set_item("is_cuda", true).ok();
                dict.set_item("device", "cuda").ok();
                ptr_value = device_ptr;
            } else {
                ptr_value = host_ptr;
            }

            // Drop shmem — DMA is complete, no need to keep the mmap alive.
            // munmap + close(fd) happen here but shm_unlink is skipped since
            // this process only opened (did not create) the shared memory.
        } else {
            ptr_value = dict
                .get_item("ptr")
                .wrap_err("metadata dict missing 'ptr' key")?
                .unwrap()
                .extract()
                .wrap_err("failed to extract ptr as u64")?;
        }

        let ptr_array = arrow::array::Int64Array::from(vec![ptr_value as i64]);
        let pinned_ptr = ptr_array.to_data().to_pyarrow(py).unwrap();

        // Free daemon entry if requested
        if free {
            match self.node.get_mut().free_pinned_memory(shared_memory_id.clone()) {
                Ok(_) => {
                    if shared_memory_id.starts_with("pool_") {
                        FREED_POOL_BUFFERS.lock().unwrap().insert(shared_memory_id.clone(), data_size as usize);
                    }
                }
                Err(_e) => {
                    tracing::warn!(
                        "[{}]重复释放页锁内存{},size={}",
                        self.node_id, shared_memory_id, data_size
                    );
                }
            }
        }

        let tuple = PyTuple::new(py, &[pinned_ptr, dict.into()]);
        let tuple = tuple?;
        Ok(tuple.into())
    }

    /// Free pinned memory registered with daemon.
    ///
    /// :param pinned_buffer: pyarrow array containing shared memory identifier
    /// :rtype: None
    #[pyo3(signature = (pinned_buffer,))]
    pub fn free_pinned_memory(&self, pinned_buffer: PyObject, py: Python) -> eyre::Result<()> {
        // Extract shared memory ID from pyarrow array
        let array_data = arrow::array::ArrayData::from_pyarrow_bound(pinned_buffer.bind(py))
            .wrap_err("failed to convert pinned_buffer to arrow array")?;
        let array = arrow::array::make_array(array_data);

        // The array should be a binary array containing the shared memory ID
        let shared_memory_id =
            if let Some(binary_array) = array.as_any().downcast_ref::<BinaryArray>() {
                if binary_array.len() != 1 {
                    eyre::bail!(
                        "expected binary array with exactly one element, got {}",
                        binary_array.len()
                    );
                }
                let bytes = binary_array.value(0);
                String::from_utf8(bytes.to_vec()).wrap_err("shared memory ID is not valid UTF-8")?
            } else if let Some(string_array) = array.as_any().downcast_ref::<StringArray>() {
                if string_array.len() != 1 {
                    eyre::bail!(
                        "expected string array with exactly one element, got {}",
                        string_array.len()
                    );
                }
                string_array.value(0).to_string()
            } else {
                eyre::bail!(
                    "FREE: pinned_buffer must be a binary or string array, got {:?}",
                    array.data_type()
                )
            };

        // Pool-mode buffers: track locally first for read-after-free detection,
        // then notify daemon for lifecycle tracking (so cleanup_all counts correctly).
        if shared_memory_id.starts_with("pool_") {
            let mut freed = FREED_POOL_BUFFERS.lock().unwrap();
            if freed.contains_key(&shared_memory_id) {
                let stored_size = freed[&shared_memory_id];
                tracing::warn!(
                    "[{}]重复释放页锁内存{},size={}",
                    self.node_id, shared_memory_id, stored_size
                );
                return Ok(());
            } else {
                freed.insert(shared_memory_id.clone(), 0);
            }
            // Fall through to daemon call for lifecycle tracking
        }

        let result = self.node.get_mut().free_pinned_memory(shared_memory_id.clone());
        match result {
            Ok(_) => {
                // Pool-mode: already tracked above in FREED_POOL_BUFFERS
            }
            Err(e) => {
                let err_msg = format!("{:#}", e);
                // Extract size from error message "already freed,size=N"
                let size_str = err_msg.split("size=").nth(1).unwrap_or("0");
                tracing::warn!(
                    "[{}]重复释放页锁内存{},size={}",
                    self.node_id, shared_memory_id, size_str
                );
            }
        }

        Ok(())
    }
}

fn err_to_pyany(err: eyre::Report, gil: Python<'_>) -> Py<PyAny> {
    PyErr::from(err)
        .into_pyobject(gil)
        .unwrap_or_else(|infallible| match infallible {})
        .into_any()
        .unbind()
}

struct Events {
    inner: Arc<Mutex<EventsInner>>,
    _cleanup_handle: NodeCleanupHandle,
}

impl Events {
    fn recv(&self, timeout: Option<Duration>) -> PyResult<Option<PyEvent>> {
        let mut inner = self.inner.blocking_lock();
        let event = match &mut *inner {
            EventsInner::Dora(events) => {
                if events.is_closed() {
                    return Err(eyre::eyre!("cannot receive from closed event stream").into());
                }
                match timeout {
                    Some(timeout) => events.recv_timeout(timeout).map(MergedEvent::Dora),
                    None => events.recv().map(MergedEvent::Dora),
                }
            }
            EventsInner::Merged(events) => futures::executor::block_on(events.next()),
        };
        Ok(event.map(|event| PyEvent { event }))
    }

    fn try_recv(&self) -> PyResult<Result<PyEvent, TryRecvError>> {
        let mut inner = self.inner.blocking_lock();
        let event = match &mut *inner {
            EventsInner::Dora(events) => {
                if events.is_closed() {
                    return Err(eyre::eyre!("cannot receive from closed event stream").into());
                }
                events.try_recv().map(MergedEvent::Dora)
            }
            EventsInner::Merged(_events) => {
                todo!("try_recv on external event stream is not yet implemented!")
            }
        };
        Ok(event.map(|event| PyEvent { event }))
    }

    async fn recv_async_timeout(&self, timeout: Option<Duration>) -> PyResult<Option<PyEvent>> {
        let mut inner = self.inner.lock().await;
        let event = match &mut *inner {
            EventsInner::Dora(events) => {
                if events.is_closed() {
                    return Err(eyre::eyre!("cannot receive from closed event stream").into());
                }
                match timeout {
                    Some(timeout) => events
                        .recv_async_timeout(timeout)
                        .await
                        .map(MergedEvent::Dora),
                    None => events.recv_async().await.map(MergedEvent::Dora),
                }
            }
            EventsInner::Merged(events) => events.next().await,
        };
        Ok(event.map(|event| PyEvent { event }))
    }

    fn drain(&self) -> Option<Vec<PyEvent>> {
        let mut inner = self.inner.blocking_lock();
        match &mut *inner {
            EventsInner::Dora(events) => match events.drain() {
                Some(items) => {
                    return Some(
                        items
                            .into_iter()
                            .map(MergedEvent::Dora)
                            .map(|event| PyEvent { event })
                            .collect(),
                    );
                }
                None => return None,
            },
            EventsInner::Merged(_events) => {
                todo!("Draining external event is not yet implemented!")
            }
        };
    }

    fn is_empty(&self) -> bool {
        let inner = self.inner.blocking_lock();
        match &*inner {
            EventsInner::Dora(events) => events.is_empty(),
            EventsInner::Merged(_events) => {
                todo!("is_empty on external event stream is not yet implemented!")
            }
        }
    }
}

#[allow(clippy::large_enum_variant)]
enum EventsInner {
    Dora(EventStream),
    Merged(Box<dyn Stream<Item = MergedEvent<PyObject>> + Unpin + Send + Sync>),
}

impl<'a> MergeExternalSend<'a, PyObject> for EventsInner {
    type Item = MergedEvent<PyObject>;

    fn merge_external_send(
        self,
        external_events: impl Stream<Item = PyObject> + Unpin + Send + Sync + 'a,
    ) -> impl Stream<Item = Self::Item> + Unpin + Send + Sync + 'a {
        let stream: Box<dyn Stream<Item = Self::Item> + Unpin + Send + Sync + 'a> = match self {
            EventsInner::Dora(events) => Box::new(events.merge_external_send(external_events)),
            EventsInner::Merged(events) => {
                let merged = events.merge_external_send(external_events);
                Box::new(merged.map(|event| match event {
                    MergedEvent::Dora(e) => MergedEvent::Dora(e),
                    MergedEvent::External(e) => MergedEvent::External(e.flatten()),
                }))
            }
        };
        stream
    }
}

impl Node {
    pub fn id(&self) -> String {
        self.node_id.to_string()
    }

    /// DORADMA fast path for read_pinned_memory: reads metadata directly from
    /// the shmem header, bypassing the daemon for zero-copy metadata retrieval.
    ///
    /// Buffer ID format: "pool_{slot}_{counter}" → shmem name: "dora_pool_{slot}"
    ///
    /// Returns `Ok(Some(result))` on success, `Ok(None)` to fall back to daemon.
    fn try_doradma_read(
        &self,
        shared_memory_id: &str,
        free: bool,
        py: Python<'_>,
    ) -> eyre::Result<Option<PyObject>> {
        // Check local freed tracking — if this buffer was already freed,
        // warn and return dummy result without proceeding to DMA.
        if FREED_POOL_BUFFERS.lock().unwrap().contains_key(shared_memory_id) {
            tracing::warn!(
                "[{}]读取不存在的页锁内存{}",
                self.node_id, shared_memory_id
            );
            let ptr_array = arrow::array::Int64Array::from(vec![0i64]);
            let pinned_ptr = ptr_array.to_data().to_pyarrow(py)
                .map_err(|e| eyre::eyre!("failed to convert to pyarrow: {}", e))?;
            let dict = PyDict::new(py);
            dict.set_item("size", 0).ok();
            let tuple = PyTuple::new(py, &[pinned_ptr, dict.into()])?;
            return Ok(Some(tuple.into()));
        }

        // Extract slot number from "pool_{slot}_{counter}"
        let parts: Vec<&str> = shared_memory_id.split('_').collect();
        if parts.len() < 3 {
            return Ok(None); // malformed pool ID
        }
        let slot: usize = match parts[1].parse() {
            Ok(s) => s,
            Err(_) => return Ok(None),
        };
        let shmem_name = format!("dora_pool_{}", slot);

        // Open shared memory
        let shmem = match ShmemConf::new().os_id(&shmem_name).open() {
            Ok(s) => s,
            Err(_) => return Ok(None), // shmem not available, fall back to daemon
        };

        let shmem_ptr = shmem.as_ptr();
        let shmem_size = shmem.len();

        // Verify DORADMA magic header
        const HEADER_MAGIC: &[u8; 8] = b"DORADMA\x00";
        const HEADER_SIZE: usize = 256;

        unsafe {
            let magic = std::slice::from_raw_parts(shmem_ptr, 8);
            if magic != HEADER_MAGIC {
                return Ok(None); // not a DORADMA shmem, fall back to daemon
            }
        }

        // Read header: [magic:8][json_len:8][data_offset:8][reserved:232]
        let json_len = unsafe {
            u64::from_le_bytes(
                (std::slice::from_raw_parts(shmem_ptr.add(8), 8))
                    .try_into()
                    .unwrap(),
            ) as usize
        };
        let data_offset = unsafe {
            u64::from_le_bytes(
                (std::slice::from_raw_parts(shmem_ptr.add(16), 8))
                    .try_into()
                    .unwrap(),
            ) as usize
        };

        // Read JSON metadata from header
        let json_slice = unsafe { std::slice::from_raw_parts(shmem_ptr.add(HEADER_SIZE), json_len) };
        let json_str = match std::str::from_utf8(json_slice) {
            Ok(s) => s,
            Err(_) => return Ok(None),
        };

        // Parse JSON to Python dict
        let metadata_dict: Bound<'_, PyDict> = match py.import("json") {
            Ok(m) => match m.call_method1("loads", (json_str,)) {
                Ok(v) => match v.downcast_into::<PyDict>() {
                    Ok(d) => d,
                    Err(_) => return Ok(None),
                },
                Err(_) => return Ok(None),
            },
            Err(_) => return Ok(None),
        };

        let size: usize = match metadata_dict.get_item("size") {
            Ok(Some(v)) => v.extract().unwrap_or(0),
            _ => 0,
        };
        if size == 0 {
            return Ok(None);
        }

        // --- Zero-copy receiver read via GPU VA ---
        // Instead of DMA copy shmem→VRAM, get the receiver's own GPU VA
        // for the shmem pages (via cudaHostRegister + cudaHostGetDevicePointer).
        // Cache both GPU VA and Shmem handle per slot:
        // keeping Shmem alive prevents munmap → stable mmap addresses and valid GPU VA.
        let device_ptr = {
            let cache = RECV_GPU_VA.lock().unwrap();
            match &cache[slot] {
                Some(slot_data) => slot_data.gpu_va + data_offset as u64,
                None => {
                    // First access: register shmem + get GPU VA + cache both
                    drop(cache);
                    let helpers = get_cuda_helpers(py)
                        .map_err(|e| eyre::eyre!("get_cuda_helpers: {}", e))?;
                    let bound = helpers.bind(py);
                    // Must register before getting device pointer
                    bound
                        .call_method1("_register_host", (shmem_ptr as u64, shmem_size))
                        .map_err(|e| eyre::eyre!("_register_host: {}", e))?;
                    let va: u64 = bound
                        .call_method1("_get_device_ptr", (shmem_ptr as u64,))
                        .map_err(|e| eyre::eyre!("_get_device_ptr: {}", e))?
                        .extract()
                        .map_err(|e| eyre::eyre!("extract gpu_va: {}", e))?;
                    let mut cache = RECV_GPU_VA.lock().unwrap();
                    cache[slot] = Some(RecvGpuSlot { _shmem: shmem, gpu_va: va });
                    va + data_offset as u64
                }
            }
        };

        // Update metadata with device info
        metadata_dict.set_item("ptr", device_ptr as i64).ok();
        metadata_dict.set_item("is_cuda", true).ok();
        metadata_dict.set_item("device", "cuda").ok();

        // Free pool-mode buffer: local tracking only (daemon lifecycle handled
        // by free_pinned_memory or read_pinned_memory free=True fallback path).
        if free {
            let mut freed = FREED_POOL_BUFFERS.lock().unwrap();
            if freed.contains_key(shared_memory_id) {
                tracing::warn!(
                    "[{}]重复释放页锁内存{},size={}",
                    self.node_id, shared_memory_id, size
                );
            } else {
                freed.insert(shared_memory_id.to_string(), size);
            }
        }

        // Build return tuple: (ptr_array, metadata_dict)
        let ptr_array = arrow::array::Int64Array::from(vec![device_ptr as i64]);
        let pinned_ptr = ptr_array.to_data().to_pyarrow(py).map_err(|e| eyre::eyre!("{}", e))?;
        let tuple = PyTuple::new(py, &[pinned_ptr, metadata_dict.into()])?;
        Ok(Some(tuple.into()))
    }
}

/// Start a runtime for Operators
///
/// :rtype: None
#[pyfunction]
pub fn start_runtime() -> eyre::Result<()> {
    dora_runtime::main().wrap_err("Dora Runtime raised an error.")
}

pub fn resolve_dataflow(dataflow: String) -> eyre::Result<PathBuf> {
    let dataflow = if source_is_url(&dataflow) {
        // try to download the shared library
        let target_path = current_dir().context("Could not access the current dir")?;
        let rt = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .context("tokio runtime failed")?;
        rt.block_on(async { download_file(&dataflow, &target_path).await })
            .wrap_err("failed to download dataflow yaml file")?
    } else {
        PathBuf::from(dataflow)
    };
    Ok(dataflow)
}

/// Build a Dataflow, exactly the same way as `dora build` command line tool.
///
///
/// :type dataflow_path: str
/// :type uv: bool, optional
/// :type coordinator_addr: str, optional
/// :type coordinator_port: int, optional
/// :type force_local: bool, optional
/// :rtype: None
#[pyfunction]
#[pyo3(signature = (dataflow_path, uv=None, coordinator_addr=None, coordinator_port=None, force_local=false))]
pub fn build(
    dataflow_path: String,
    uv: Option<bool>,
    coordinator_addr: Option<String>,
    coordinator_port: Option<u16>,
    force_local: bool,
) -> eyre::Result<()> {
    dora_cli::build(
        dataflow_path,
        coordinator_addr.map(|addr| addr.parse().unwrap()),
        coordinator_port,
        uv.unwrap_or_default(),
        force_local,
    )
}

/// Run a Dataflow, exactly the same way as `dora run` command line tool.
///
/// :type dataflow_path: str
/// :type uv: bool, optional
/// :type stop_after: float, optional
/// :rtype: None
#[pyfunction]
#[pyo3(signature = (dataflow_path, uv=None, stop_after=None))]
pub fn run(dataflow_path: String, uv: Option<bool>, stop_after: Option<f64>) -> eyre::Result<()> {
    use dora_cli::Executable;

    let stop_after_duration = stop_after.map(std::time::Duration::from_secs_f64);
    let mut run = dora_cli::RunCommand::new(dataflow_path);
    if let Some(uv) = uv {
        run.uv = uv;
    }
    if let Some(duration) = stop_after_duration {
        run.stop_after = Some(duration);
    }
    let rt = tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()
        .context("tokio runtime failed")?;
    rt.block_on(run.execute())
}

#[pymodule]
fn dora(_py: Python, m: Bound<'_, PyModule>) -> PyResult<()> {
    dora_ros2_bridge_python::create_dora_ros2_bridge_module(&m)?;

    m.add_function(wrap_pyfunction!(start_runtime, &m)?)?;
    m.add_function(wrap_pyfunction!(run, &m)?)?;
    m.add_function(wrap_pyfunction!(build, &m)?)?;
    m.add_class::<Node>()?;
    m.setattr("__version__", env!("CARGO_PKG_VERSION"))?;
    m.setattr("__author__", "Dora-rs Authors")?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use shared_memory_extended::ShmemConf;

    #[test]
    fn test_shmem_creation() {
        // Test that ShmemConf can create and write to shared memory
        let size = 8000;
        let shmem_conf = ShmemConf::new().size(size).writable(true);

        let mut shmem = shmem_conf.create().expect("failed to create shared memory");

        // Write to shared memory
        let slice = unsafe { shmem.as_slice_mut() };
        slice[0] = 0x42;
        assert_eq!(slice[0], 0x42);

        // Write pattern
        for i in 0..size.min(100) {
            slice[i] = (i % 256) as u8;
        }

        // Read back
        for i in 0..size.min(100) {
            assert_eq!(slice[i], (i % 256) as u8);
        }
    }
}
