/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_ADORA_OPERATOR_API_C__
#define __RUST_ADORA_OPERATOR_API_C__
#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>

/** \brief
 *  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout
 */
typedef struct Vec_uint8 {
    /** <No documentation available> */
    uint8_t * ptr;

    /** <No documentation available> */
    size_t len;

    /** <No documentation available> */
    size_t cap;
} Vec_uint8_t;

/** <No documentation available> */
typedef struct AdoraResult {
    /** <No documentation available> */
    Vec_uint8_t * error;
} AdoraResult_t;

/** <No documentation available> */
typedef struct AdoraDropOperator {
    /** <No documentation available> */
    AdoraResult_t (*drop_operator)(void *);
} AdoraDropOperator_t;

/** <No documentation available> */
typedef struct AdoraInitResult {
    /** <No documentation available> */
    AdoraResult_t result;

    /** <No documentation available> */
    void * operator_context;
} AdoraInitResult_t;

/** <No documentation available> */
typedef struct AdoraInitOperator {
    /** <No documentation available> */
    AdoraInitResult_t (*init_operator)(void);
} AdoraInitOperator_t;

/** <No documentation available> */
/** \remark Has the same ABI as `uint8_t` **/
#ifdef DOXYGEN
typedef
#endif
enum AdoraStatus {
    /** <No documentation available> */
    ADORA_STATUS_CONTINUE = 0,
    /** <No documentation available> */
    ADORA_STATUS_STOP = 1,
    /** <No documentation available> */
    ADORA_STATUS_STOP_ALL = 2,
}
#ifndef DOXYGEN
; typedef uint8_t
#endif
AdoraStatus_t;

/** <No documentation available> */
typedef struct OnEventResult {
    /** <No documentation available> */
    AdoraResult_t result;

    /** <No documentation available> */
    AdoraStatus_t status;
} OnEventResult_t;

/** <No documentation available> */
typedef struct Input Input_t;


#include <stdbool.h>

/** <No documentation available> */
typedef struct RawEvent {
    /** <No documentation available> */
    Input_t * input;

    /** <No documentation available> */
    Vec_uint8_t input_closed;

    /** <No documentation available> */
    bool stop;

    /** <No documentation available> */
    Vec_uint8_t error;
} RawEvent_t;

/** <No documentation available> */
typedef struct Output Output_t;

/** \brief
 *  `Arc<dyn Send + Sync + Fn(A1) -> Ret>`
 */
typedef struct ArcDynFn1_AdoraResult_Output {
    /** <No documentation available> */
    void * env_ptr;

    /** <No documentation available> */
    AdoraResult_t (*call)(void *, Output_t);

    /** <No documentation available> */
    void (*release)(void *);

    /** <No documentation available> */
    void (*retain)(void *);
} ArcDynFn1_AdoraResult_Output_t;

/** <No documentation available> */
typedef struct SendOutput {
    /** <No documentation available> */
    ArcDynFn1_AdoraResult_Output_t send_output;
} SendOutput_t;

/** <No documentation available> */
typedef struct AdoraOnEvent {
    /** <No documentation available> */
    OnEventResult_t (*on_event)(RawEvent_t *, SendOutput_t const *, void *);
} AdoraOnEvent_t;

/** <No documentation available> */
typedef struct Metadata {
    /** <No documentation available> */
    Vec_uint8_t open_telemetry_context;
} Metadata_t;

/** <No documentation available> */
void
adora_free_data (
    Vec_uint8_t _data);

/** <No documentation available> */
void
adora_free_input_id (
    char * _input_id);

/** <No documentation available> */
Vec_uint8_t
adora_read_data (
    Input_t * input);

/** <No documentation available> */
char *
adora_read_input_id (
    Input_t const * input);

/** <No documentation available> */
AdoraResult_t
adora_send_operator_output (
    SendOutput_t const * send_output,
    char const * id,
    uint8_t const * data_ptr,
    size_t data_len);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_ADORA_OPERATOR_API_C__ */
